version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Compiling"
      - npm run build
  post_build:
    commands:
      - echo "Build completed on $(date)"
# Include only the files required for your application to run.
artifacts:
  files:
    - build/**/*
    - appspec.yml
    - scripts/before_install.sh
    - src/**/*
    - package.json
    - scripts/start_server.sh
    - scripts/before_install.sh
